/**
 * Supported platform types for identity and social profiles
 * Includes blockchain networks, name services, and social platforms
 * @public
 */
export enum Platform {
  ailayer = "ailayer",
  alienx = "alienx",
  aptos = "aptos",
  arbitrum = "arbitrum",
  basenames = "basenames",
  bilibili = "bilibili",
  bitcoin = "bitcoin",
  bluesky = "bluesky",
  box = "box",
  bsc = "bsc",
  calendly = "calendly",
  ckb = "ckb",
  clusters = "clusters",
  coingecko = "coingecko",
  cosmos = "cosmos",
  cyberconnect = "cyberconnect",
  deepdao = "deepdao",
  degenscore = "degenscore",
  discord = "discord",
  doge = "doge",
  dotbit = "dotbit",
  dns = "dns",
  ecp = "ecp",
  edgeless = "edgeless",
  efp = "efp",
  ens = "ens",
  ethos = "ethos",
  ethereum = "ethereum",
  facebook = "facebook",
  farcaster = "farcaster",
  firefly = "firefly",
  genome = "genome",
  github = "github",
  gitcoin = "gitcoin",
  gnosis = "gnosis",
  gravity = "gravity",
  guild = "guild",
  hackernews = "hackernews",
  hey = "hey",
  humanode = "humanode",
  humanpassport = "humanpassport",
  instagram = "instagram",
  interface = "interface",
  keybase = "keybase",
  lens = "lens",
  lightlink = "lightlink",
  linkedin = "linkedin",
  linea = "linea",
  lobsters = "lobsters",
  manta = "manta",
  matters = "matters",
  medium = "medium",
  merlin = "merlin",
  minds = "minds",
  mint = "mint",
  mirror = "mirror",
  mode = "mode",
  mstdnjp = "mstdnjp",
  near = "near",
  nextid = "nextid",
  nostr = "nostr",
  opensea = "opensea",
  paragraph = "paragraph",
  philand = "philand",
  poap = "poap",
  polymarket = "polymarket",
  pumpfun = "pumpfun",
  reddit = "reddit",
  scroll = "scroll",
  seekerid = "seekerid",
  self_xyz = "self_xyz",
  sns = "sns",
  snapshot = "snapshot",
  solana = "solana",
  space_id = "space_id",
  stacks = "stacks",
  talent = "talentprotocol",
  taiko = "taiko",
  telegram = "telegram",
  threads = "threads",
  tiktok = "tiktok",
  tomo = "tomo",
  ton = "ton",
  tron = "tron",
  twitter = "twitter",
  uniswap = "uniswap",
  unstoppableDomains = "unstoppabledomains",
  url = "url",
  v2ex = "v2ex",
  webacy = "webacy",
  website = "website",
  weibo = "weibo",
  whatsapp = "whatsapp",
  world_id = "world_id",
  youtube = "youtube",
  zeta = "zeta",
  zkfair = "zkfair",
  zkme = "zkme",
  zora = "zora",
}

/**
 * Platform metadata structure
 * Contains display and functional information about a platform
 * @public
 */
export interface PlatformType {
  color?: string;
  icon?: string;
  label: string;
  description?: string;
  urlPrefix?: string;
  ensText?: string[];
  registerlink?: string;
  editUrlPrefix?: string;
}
